name: ðŸ›¸ Deploy to WordPress.org
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: ðŸŽ‰ New release
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get the latest code
        uses: actions/checkout@v2

      - name: ðŸš€ WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ secrets.SLUG }}

      #      - name: ðŸ“‹ Upload release asset
      #        uses: rops/action-gh-release@v1
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #          GITHUB_REPOSITORY: viivue/acf-icomoon
      #        with:
      #          upload_url: ${{ github.event.release.upload_url }}
      #          #asset_path: ${{ steps.deploy.outputs.zip-path }}
      #          #asset_name: ${{ github.event.repository.name }}.zip
      #          asset_content_type: application/zip

      - name: ðŸ“‚ Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip